# Generated by Django 6.0.5 on 2026-05-26 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('unknown_face', 'Unknown Face Detected'), ('liveness_fail', 'Liveness Check Failed'), ('multiple_fail', 'Multiple Failed Attempts'), ('system_error', 'System Error')], max_length=30)),
                ('message', models.TextField()),
                ('camera_id', models.CharField(blank=True, max_length=100)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fg_alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
