# Generated by Codex on 2026-05-31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recognition', '0001_initial'),
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='camera_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='ZoneRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_rules', to='recognition.enrolledperson')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='zones.zone')),
            ],
            options={
                'db_table': 'fg_zone_rules',
                'unique_together': {('zone', 'person')},
            },
        ),
        migrations.CreateModel(
            name='AccessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('granted', 'Granted'), ('denied', 'Denied'), ('error', 'Error')], max_length=20)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('camera_id', models.CharField(blank=True, max_length=100)),
                ('liveness_pass', models.BooleanField(default=False)),
                ('denial_reason', models.CharField(blank=True, max_length=255)),
                ('processing_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('frame_path', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_events', to='recognition.enrolledperson')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zone_access_events', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_events', to='zones.zone')),
            ],
            options={
                'db_table': 'fg_zone_access_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['zone', 'created_at'], name='fg_zone_acc_zone_id_4a414b_idx')],
            },
        ),
    ]
