# Generated by Django 6.0.5 on 2026-05-30 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolledPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('employee_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('enrolled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fg_enrolled_persons',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FaceEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='enrolment/')),
                ('model_name', models.CharField(default='VGG-Face', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='recognition.enrolledperson')),
            ],
            options={
                'db_table': 'fg_face_embeddings',
            },
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('granted', 'Access Granted'), ('denied', 'Access Denied'), ('error', 'Error')], max_length=10)),
                ('confidence', models.FloatField(default=0.0)),
                ('distance', models.FloatField(default=1.0)),
                ('liveness_pass', models.BooleanField(default=False)),
                ('frame_image', models.ImageField(blank=True, upload_to='verify_frames/')),
                ('camera_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('error_detail', models.TextField(blank=True)),
                ('matched_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to='recognition.enrolledperson')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fg_verification_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
