# Generated by Codex on 2026-05-31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledperson',
            name='user',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='face_profile',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
